services:
  pgsql:
    image: postgres:16
    container_name: postgres
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: edmiya.dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - pgsql
volumes:
  postgres_data: